modmap:
  #  - name: escapando Control
  #    remap:
  #      KEY_LEFTCTRL:
  #        held: KEY_RIGHTCTRL
  #        alone: KEY_RIGHTCTRL
  #        alone_timeout_millis: 500
keymap:
  - name: Mac Home End Keys
    remap:
      Alt-KEY_LEFT: KEY_HOME
      Alt-KEY_RIGHT: KEY_END
      Alt-KEY_UP: CONTROL-KEY_HOME
      Alt-KEY_DOWN: CONTROL-KEY_END
